package totan.bodaster.com;

import java.util.ArrayList;

public class EncounterTableEntry extends ArrayList<String> {
    //Constants
    private final static int ADJ_IDX = 0;
    private final static int SUBJ_IDX = 1;
    private final static int MATRIX_LETTER_IDX = 2;

    public final static String[] EMPTY_ENTRY = {"Empty", "Empty", "Empty"};

    //Constants for Encounter table adjectives (=lines in Matrices)
    public final static String ADULTEROUS = "Adulterous";
    public final static String ALLPOWERFUL = "All-Powerful";
    public final static String ANCIENT = "Ancient";
    public final static String ANGRY = "Angry";
    public final static String ANY = "<see card for subject>";
    public final static String ARMED = "Armed";
    public final static String BEAUTIFUL = "Beautiful";
    public final static String BLACK = "Black";
    public final static String BLIND = "Blind";
    public final static String BLOODTHIRSTY = "Bloodthirsty";
    public final static String BUMBLING = "Bumbling";
    public final static String BUSY = "Busy";
    public final static String CHEATING = "Cheating";
    public final static String COLD = "Cold";
    public final static String CON = "Con";
    public final static String CRAFTY = "Crafty";
    public final static String DANGEROUS = "Dangerous";
    public final static String DARK = "Dark";
    public final static String DEMONIC = "Demonic";
    public final static String DESTITUTE = "Destitute";
    public final static String DISEASED = "Diseased";
    public final static String DISGUISED = "Disguised";
    public final static String DOOMED = "Doomed";
    public final static String DOOMSAYING = "Doomsaying";
    public final static String DRUNKEN = "Drunken";
    public final static String DYING = "Dying";
    public final static String EGGOF = "Egg of";
    public final static String ENCHANTED = "Enchanted";
    public final static String EVIL = "Evil";
    public final static String FABULOUS = "Fabulous";
    public final static String FALSE = "False";
    public final static String FEARFUL = "Fearful";
    public final static String FINE = "Fine";
    public final static String FLYING = "Flying";
    public final static String FOOLISH = "Foolish";
    public final static String FRIENDLY = "Friendly";
    public final static String GARRULOUS = "Garrulous";
    public final static String GHOSTLY = "Ghostly";
    public final static String GLITTERING = "Glittering";
    public final static String GREEDY = "Greedy";
    public final static String GUARDED = "Guarded";
    public final static String HANDSOME = "Handsome";
    public final static String HAPPY = "Happy";
    public final static String HEALER = "Healer";
    public final static String HEARTRENDING = "Heart-Rending";
    public final static String HIDDEN = "Hidden";
    public final static String HIDEOUS = "Hideous";
    public final static String HORRIBLE = "Horrible";
    public final static String HOUSE = "House";
    public final static String HUGE = "Huge";
    public final static String HUNGRY = "Hungry";
    public final static String HYPNOTIC = "Hypnotic";
    public final static String IMPRISONED = "Imprisoned";
    public final static String IMPUDENT = "Impudent";
    public final static String INSANE = "Insane";
    public final static String JEWELED = "Jeweled";
    public final static String KINDLY = "Kindly";
    public final static String LEARNED = "Learned";
    public final static String LONELY = "Lonely";
    public final static String LOST = "Lost";
    public final static String LOVESICK = "Lovesick";
    public final static String MAD = "Mad";
    public final static String MAGICAL = "Magical";
    public final static String MALICIOUS = "Malicious";
    public final static String MERRY = "Merry";
    public final static String MIGHTY = "Mighty";
    public final static String MILD = "Mild";
    public final static String MINOR = "Minor";
    public final static String MULTITUDINOUS = "Multitudinous";
    public final static String MYSTERIOUS = "Mysterious";
    public final static String MYSTIC = "Mystic";
    public final static String NEEDY = "Needy";
    public final static String NOBLE = "Noble";
    public final static String OLD = "Old";
    public final static String POSSESSED = "Possessed";
    public final static String POWERFUL = "Powerful";
    public final static String PRACTICAL = "Practical";
    public final static String PUISSANT = "Puissant";
    public final static String REPENTANT = "Repentant";
    public final static String ROCK = "Rock";
    public final static String RUINED = "Ruined";
    public final static String RUNAWAY = "Runaway";
    public final static String SAD = "Sad";
    public final static String SAND = "Sand";
    public final static String SECRET = "Secret";
    public final static String SELFSACRIFICIAL = "Self-Sacrificial";
    public final static String SKILLFUL = "Skillful";
    public final static String SMALL = "Small";
    public final static String STRANGE = "Strange";
    public final static String TALKING = "Talking";
    public final static String TERRIBLE = "Terrible";
    public final static String TOOTHLESS = "Toothless";
    public final static String TRAPPED = "Trapped";
    public final static String TREACHEROUS = "Treacherous";
    public final static String UGLY = "Ugly";
    public final static String UNKNOWN = "Unknown";
    public final static String VENGEFUL = "Vengeful";
    public final static String WEALTHY = "Wealthy";
    public final static String WHIRLING = "Whirling";
    public final static String WICKED = "Wicked";
    public final static String WISE = "Wise";
    public final static String WONDERFUL = "Wonderful";

    //Constants for Encounter table subjects
    public final static String EFREET = "'Efreet";
    public final static String EFREETEH = "'Efreeteh";
    public final static String ARTIFACT = "Artifact";
    public final static String BEAST = "Beast";
    public final static String BEGGAR = "Beggar";
    public final static String BRIGANDS = "Brigands";
    public final static String CAPTAIN = "Captain";
    public final static String CITY = "City";
    public final static String CREATURES = "Creatures";
    public final static String CUSTOMS = "Customs";
    public final static String DERVISH = "Dervish";
    public final static String ENCHANTRESS = "Enchantress";
    public final static String FIRE = "Fire";
    public final static String GAME = "Game";
    public final static String GOOLEH = "Gooleh";
    public final static String HAG = "Hag";
    public final static String HUNCHBACK = "Hunchback";
    public final static String JOKERENCHANTRESS = "Joker Enchantress";
    public final static String JOKERWIZARD = "Joker Wizard";
    public final static String MAIDEN = "Maiden";
    public final static String MAN = "Man";
    public final static String MERCHANT = "Merchant";
    public final static String MERMAN = "Merman";
    public final static String NEERDOWELL = "Ne'er-do-well";
    public final static String ROC = "Roc";
    public final static String PRINCE = "Prince";
    public final static String PRINCESS = "Princess";
    public final static String PROPHET = "Prophet";
    public final static String RIVER = "River";
    public final static String SAGE = "Sage";
    public final static String SHOALS = "Shoals";
    public final static String SLAVE = "Slave";
    public final static String SLIDE = "Slide";
    public final static String SOLDIER = "Soldier";
    public final static String STORM = "Storm";
    public final static String THIEF = "Thief";
    public final static String TRAPDOOR = "Trapdoor";
    public final static String TREASURE = "Treasure";
    public final static String VIZIER = "Vizier";
    public final static String WHIRLPOOL = "Whirlpool";
    public final static String WIZARD = "Wizard";

    //Constants for encounter table rows, where subject exists (table 1-83)
    public final static String[] ADULTEROUS_SLAVE = {ADULTEROUS, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] ADULTEROUS_NEERDOWELL = {ADULTEROUS, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] ADULTEROUS_THIEF = {ADULTEROUS, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] ALLPOWERFUL_EFREET = {ALLPOWERFUL, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] ALLPOWERFUL_EFREETEH = {ALLPOWERFUL, EFREETEH, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] ANCIENT_CITY = {ANCIENT, CITY, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] ANGRY_EFREETEH = {ANGRY, EFREETEH, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] ANGRY_EFREET = {ANGRY, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] ARMED_THIEF = {ARMED, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] ARMED_NEERDOWELL = {ARMED, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] ARMED_SLAVE = {ARMED, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] BEAUTIFUL_ENCHANTRESS = {BEAUTIFUL, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] BEAUTIFUL_SHOALS = {BEAUTIFUL, SHOALS, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] BEAUTIFUL_PRINCESS = {BEAUTIFUL, PRINCESS, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] BEAUTIFUL_EFREETEH = {BEAUTIFUL, EFREETEH, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] BEAUTIFUL_MAIDEN = {BEAUTIFUL, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] BLACK_WHIRLPOOL = {BLACK, WHIRLPOOL, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] BLACK_RIVER = {BLACK, RIVER, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] BLIND_MAN = {BLIND, MAN, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] BLOODTHIRSTY_BRIGANDS = {BLOODTHIRSTY, BRIGANDS, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] BLOODTHIRSTY_ENCHANTRESS = {BLOODTHIRSTY, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] BLOODTHIRSTY_WIZARD = {BLOODTHIRSTY, WIZARD, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] BUMBLING_WIZARD = {BUMBLING, WIZARD, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] BUMBLING_ENCHANTRESS = {BUMBLING, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] BUSY_SLAVE = {BUSY, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] CHEATING_MERCHANT = {CHEATING, MERCHANT, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] COLD_WIZARD = {COLD, WIZARD, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] COLD_ENCHANTRESS = {COLD, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] CON_GAME = {CON, GAME, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] CRAFTY_WIZARD = {CRAFTY, WIZARD, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] CRAFTY_ENCHANTRESS = {CRAFTY, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] CRAFTY_HAG = {CRAFTY, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] CRAFTY_NEERDOWELL = {CRAFTY, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] CRAFTY_BEGGAR = {CRAFTY, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DANGEROUS_HUNCHBACK = {DANGEROUS, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DANGEROUS_BEGGAR = {DANGEROUS, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DANGEROUS_HAG = {DANGEROUS, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DARK_RIVER = {DARK, RIVER, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] DARK_CREATURES = {DARK, CREATURES, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] DEMONIC_EFREET = {DEMONIC, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] DEMONIC_EFREETEH = {DEMONIC, EFREETEH, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] DESTITUTE_PROPHET = {DESTITUTE, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] DESTITUTE_MERCHANT = {DESTITUTE, MERCHANT, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] DESTITUTE_BEGGAR = {DESTITUTE, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DESTITUTE_NEERDOWELL = {DESTITUTE, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DESTITUTE_PRINCE = {DESTITUTE, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] DESTITUTE_THIEF = {DESTITUTE, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DESTITUTE_HAG = {DESTITUTE, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DESTITUTE_SAGE = {DESTITUTE, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] DESTITUTE_MAIDEN = {DESTITUTE, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] DESTITUTE_HUNCHBACK = {DESTITUTE, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DISEASED_HUNCHBACK = {DISEASED, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DISEASED_HAG = {DISEASED, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DISGUISED_BEGGAR = {DISGUISED, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DISGUISED_MAIDEN = {DISGUISED, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] DISGUISED_SOLDIER = {DISGUISED, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] DISGUISED_DERVISH = {DISGUISED, DERVISH, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] DISGUISED_MERCHANT = {DISGUISED, MERCHANT, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] DISGUISED_SLAVE = {DISGUISED, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DISGUISED_HUNCHBACK = {DISGUISED, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DOOMSAYING_PROPHET = {DOOMSAYING, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] DRUNKEN_BEGGAR = {DRUNKEN, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DRUNKEN_NEERDOWELL = {DRUNKEN, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DRUNKEN_HUNCHBACK = {DRUNKEN, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DRUNKEN_HAG = {DRUNKEN, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DRUNKEN_SLAVE = {DRUNKEN, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DRUNKEN_THIEF = {DRUNKEN, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DYING_HAG = {DYING, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DYING_BEGGAR = {DYING, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DYING_HUNCHBACK = {DYING, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] EGGOF_ROC = {EGGOF, ROC, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] ENCHANTED_MAIDEN = {ENCHANTED, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] ENCHANTED_BEAST = {ENCHANTED, BEAST, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] ENCHANTED_SOLDIER = {ENCHANTED, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] ENCHANTED_MERCHANT = {ENCHANTED, MERCHANT, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] ENCHANTED_SAGE = {ENCHANTED, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] ENCHANTED_HUNCHBACK = {ENCHANTED, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] EVIL_ENCHANTRESS = {EVIL, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] EVIL_EFREETEH = {EVIL, EFREETEH, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] FABULOUS_TREASURE = {FABULOUS, TREASURE, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] FALSE_PROPHET = {FALSE, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FALSE_SAGE = {FALSE, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FEARFUL_CAPTAIN = {FEARFUL, CAPTAIN, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] FINE_BEAST = {FINE, BEAST, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] FLYING_CREATURES = {FLYING, CREATURES, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] FOOLISH_SLAVE = {FOOLISH, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] FOOLISH_NEERDOWELL = {FOOLISH, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] FOOLISH_PRINCE = {FOOLISH, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FOOLISH_THIEF = {FOOLISH, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] FOOLISH_PRINCESS = {FOOLISH, PRINCESS, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FOOLISH_MAIDEN = {FOOLISH, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] FOOLISH_SOLDIER = {FOOLISH, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] FRIENDLY_MERMAN = {FRIENDLY, MERMAN, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] FRIENDLY_HUNCHBACK = {FRIENDLY, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] FRIENDLY_HAG = {FRIENDLY, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] FRIENDLY_MAIDEN = {FRIENDLY, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] FRIENDLY_SOLDIER = {FRIENDLY, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] FRIENDLY_PRINCESS = {FRIENDLY, PRINCESS, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FRIENDLY_BEGGAR = {FRIENDLY, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] FRIENDLY_MERCHANT = {FRIENDLY, MERCHANT, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FRIENDLY_PROPHET = {FRIENDLY, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] GARRULOUS_SOLDIER = {GARRULOUS, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] GARRULOUS_MERCHANT = {GARRULOUS, MERCHANT, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] GARRULOUS_SAGE = {GARRULOUS, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] GARRULOUS_DERVISH = {GARRULOUS, DERVISH, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] GARRULOUS_MAIDEN = {GARRULOUS, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] GARRULOUS_PRINCE = {GARRULOUS, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] GHOSTLY_BEAST = {GHOSTLY, BEAST, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] GLITTERING_ARTIFACT = {GLITTERING, ARTIFACT, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] GREEDY_CAPTAIN = {GREEDY, CAPTAIN, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] GREEDY_NEERDOWELL = {GREEDY, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] GREEDY_THIEF = {GREEDY, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] GUARDED_TREASURE = {GUARDED, TREASURE, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] HANDSOME_SOLDIER = {HANDSOME, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] HANDSOME_MERCHANT = {HANDSOME, MERCHANT, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] HANDSOME_PRINCE = {HANDSOME, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] HAPPY_NEERDOWELL = {HAPPY, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] HAPPY_SLAVE = {HAPPY, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] HEALER_SAGE = {HEALER, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] HEARTRENDING_HAG = {HEARTRENDING, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] HEARTRENDING_BEGGAR = {HEARTRENDING, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] HIDDEN_CITY = {HIDDEN, CITY, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] HIDDEN_TRAPDOOR = {HIDDEN, TRAPDOOR, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] HIDEOUS_BEGGAR = {HIDEOUS, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] HIDEOUS_HUNCHBACK = {HIDEOUS, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] HORRIBLE_CREATURES = {HORRIBLE, CREATURES, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] HOUSE_FIRE = {HOUSE, FIRE, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] HUGE_WHIRLPOOL = {HUGE, WHIRLPOOL, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] HUNGRY_CREATURES = {HUNGRY, CREATURES, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] HUNGRY_GOOLEH = {HUNGRY, GOOLEH, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] HYPNOTIC_HAG = {HYPNOTIC, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] HYPNOTIC_BEGGAR = {HYPNOTIC, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] IMPRISONED_MAIDEN = {IMPRISONED, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] IMPRISONED_PRINCE = {IMPRISONED, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] IMPRISONED_PROPHET = {IMPRISONED, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] IMPRISONED_PRINCESS = {IMPRISONED, PRINCESS, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] IMPUDENT_HAG = {IMPUDENT, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] IMPUDENT_HUNCHBACK = {IMPUDENT, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] IMPUDENT_BEGGAR = {IMPUDENT, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] INSANE_HUNCHBACK = {INSANE, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] INSANE_BEGGAR = {INSANE, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] INSANE_HAG = {INSANE, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] JEWELED_TRAPDOOR = {JEWELED, TRAPDOOR, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] KINDLY_EFREET = {KINDLY, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] KINDLY_MERCHANT = {KINDLY, MERCHANT, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] LEARNED_EFREET = {LEARNED, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] LEARNED_EFREETEH = {LEARNED, EFREETEH, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] LEARNED_WIZARD = {LEARNED, WIZARD, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] LONELY_PRINCE = {LONELY, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LONELY_MAIDEN = {LONELY, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] LONELY_PROPHET = {LONELY, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LONELY_SOLDIER = {LONELY, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] LONELY_PRINCESS = {LONELY, PRINCESS, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LOST_MERCHANT = {LOST, MERCHANT, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] LOST_SAGE = {LOST, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LOST_DERVISH = {LOST, DERVISH, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] LOST_SOLDIER = {LOST, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] LOST_PROPHET = {LOST, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LOST_MAIDEN = {LOST, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] LOST_PRINCE = {LOST, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LOVESICK_MAIDEN = {LOVESICK, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] LOVESICK_THIEF = {LOVESICK, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] LOVESICK_NEERDOWELL = {LOVESICK, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] LOVESICK_HAG = {LOVESICK, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] LOVESICK_PRINCE = {LOVESICK, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LOVESICK_BEGGAR = {LOVESICK, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] LOVESICK_SOLDIER = {LOVESICK, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] LOVESICK_EFREETEH = {LOVESICK, EFREETEH, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] LOVESICK_HUNCHBACK = {LOVESICK, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] LOVESICK_SLAVE = {LOVESICK, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] LOVESICK_EFREET = {LOVESICK, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] MAD_SLAVE = {MAD, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] MAD_CAPTAIN = {MAD, CAPTAIN, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] MAD_PROPHET = {MAD, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] MAD_SAGE = {MAD, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] MAD_SOLDIER = {MAD, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] MAD_THIEF = {MAD, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] MAD_ENCHANTRESS = {MAD, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] MAD_WIZARD = {MAD, WIZARD, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] MAD_MAIDEN = {MAD, MAIDEN, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] MAD_NEERDOWELL = {MAD, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] MAGICAL_STORM = {MAGICAL, STORM, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] MALICIOUS_MERMAN = {MALICIOUS, MERMAN, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] MERRY_BRIGANDS = {MERRY, BRIGANDS, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] MIGHTY_WIZARD = {MIGHTY, WIZARD, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] MIGHTY_ENCHANTRESS = {MIGHTY, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] MILD_STORM = {MILD, STORM, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] MINOR_TREASURE = {MINOR, TREASURE, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] MULTITUDINOUS_BRIGANDS = {MULTITUDINOUS, BRIGANDS, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] MYSTERIOUS_TRAPDOOR = {MYSTERIOUS, TRAPDOOR, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] MYSTERIOUS_RIVER = {MYSTERIOUS, RIVER, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] MYSTIC_FIRE = {MYSTIC, FIRE, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] NEEDY_THIEF = {NEEDY, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] NEEDY_NEERDOWELL = {NEEDY, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] NOBLE_EFREET = {NOBLE, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] NOBLE_ENCHANTRESS = {NOBLE, ENCHANTRESS, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] NOBLE_WIZARD = {NOBLE, WIZARD, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] OLD_MAN = {OLD, MAN, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] POSSESSED_HUNCHBACK = {POSSESSED, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] POWERFUL_DERVISH = {POWERFUL, DERVISH, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] POWERFUL_WIZARD = {POWERFUL, WIZARD, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] POWERFUL_SLAVE = {POWERFUL, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] PRACTICAL_JOKERWIZARD = {PRACTICAL, JOKERWIZARD, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] PRACTICAL_JOKERENCHANTRESS = {PRACTICAL, JOKERENCHANTRESS, ReactionMatrix.MATRIX_LETTER_O};
    public final static String[] PUISSANT_SOLDIER = {PUISSANT, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] REPENTANT_THIEF = {REPENTANT, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] REPENTANT_NEERDOWELL = {REPENTANT, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] REPENTANT_MERCHANT = {REPENTANT, MERCHANT, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] ROCK_SLIDE = {ROCK, SLIDE, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] RUINED_CITY = {RUINED, CITY, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] RUNAWAY_SLAVE = {RUNAWAY, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] RUNAWAY_NEERDOWELL = {RUNAWAY, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] SAD_GOOLEH = {SAD, GOOLEH, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] SAND_STORM = {SAND, STORM, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] SECRET_TRAPDOOR = {SECRET, TRAPDOOR, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] SKILLFUL_THIEF = {SKILLFUL, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] SMALL_ARTIFACT = {SMALL, ARTIFACT, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] STRANGE_ARTIFACT = {STRANGE, ARTIFACT, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] STRANGE_CUSTOMS = {STRANGE, CUSTOMS, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] TALKING_BEAST = {TALKING, BEAST, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] TERRIBLE_STORM = {TERRIBLE, STORM, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] TOOTHLESS_HUNCHBACK = {TOOTHLESS, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] TOOTHLESS_HAG = {TOOTHLESS, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] TRAPPED_EFREET = {TRAPPED, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] TREACHEROUS_SHOALS = {TREACHEROUS, SHOALS, ReactionMatrix.MATRIX_LETTER_F};
    public final static String[] UGLY_BEGGAR = {UGLY, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] UGLY_HAG = {UGLY, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] UNKNOWN_BEAST = {UNKNOWN, BEAST, ReactionMatrix.MATRIX_LETTER_J};
    public final static String[] VENGEFUL_SOLDIER = {VENGEFUL, SOLDIER, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] VENGEFUL_SAGE = {VENGEFUL, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] VENGEFUL_PRINCESS = {VENGEFUL, PRINCESS, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] VENGEFUL_EFREET = {VENGEFUL, EFREET, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] VENGEFUL_PRINCE = {VENGEFUL, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WEALTHY_NEERDOWELL = {WEALTHY, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] WEALTHY_MERCHANT_L = {WEALTHY, MERCHANT, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] WEALTHY_MERCHANT_D = {WEALTHY, MERCHANT, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] WEALTHY_PRINCESS = {WEALTHY, PRINCESS, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WHIRLING_DERVISH = {WHIRLING, DERVISH, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] WICKED_HAG = {WICKED, HAG, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] WICKED_VIZIER = {WICKED, VIZIER, ReactionMatrix.MATRIX_LETTER_I};
    public final static String[] WICKED_DERVISH = {WICKED, DERVISH, ReactionMatrix.MATRIX_LETTER_L};
    public final static String[] WICKED_BEGGAR = {WICKED, BEGGAR, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] WICKED_PROPHET = {WICKED, PROPHET, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WICKED_HUNCHBACK = {WICKED, HUNCHBACK, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] WICKED_SAGE = {WICKED, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WICKED_NEERDOWELL = {WICKED, NEERDOWELL, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] WISE_SAGE = {WISE, SAGE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WISE_THIEF = {WISE, THIEF, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] WISE_SLAVE = {WISE, SLAVE, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] WISE_PRINCE = {WISE, PRINCE, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WISE_MERCHANT = {WISE, MERCHANT, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] WONDERFUL_ARTIFACT = {WONDERFUL, ARTIFACT, ReactionMatrix.MATRIX_LETTER_E};
    public final static String[] WONDERFUL_TREASURE = {WONDERFUL, TREASURE, ReactionMatrix.MATRIX_LETTER_E};

    //Constant for encounter table rows, where subject is empty (table 84-121)
    public final static String[] ADULTEROUS_ANY_D = {ADULTEROUS, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] ALLPOWERFUL_ANY_M = {ALLPOWERFUL, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] ALLPOWERFUL_ANY_B = {ALLPOWERFUL, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] ANGRY_ANY_M = {ANGRY, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] ARMED_ANY_D = {ARMED, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] BEAUTIFUL_ANY_A = {BEAUTIFUL, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] BEAUTIFUL_ANY_B = {BEAUTIFUL, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] BEAUTIFUL_ANY_M = {BEAUTIFUL, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] BUMBLING_ANY_B = {BUMBLING, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] BUSY_ANY_D = {BUSY, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] CRAFTY_ANY_C = {CRAFTY, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] CRAFTY_ANY_B = {CRAFTY, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] CRAFTY_ANY_D = {CRAFTY, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DANGEROUS_ANY_C = {DANGEROUS, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DEMONIC_ANY_M = {DEMONIC, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] DESTITUTE_ANY_A = {DESTITUTE, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] DESTITUTE_ANY_C = {DESTITUTE, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DESTITUTE_ANY_D = {DESTITUTE, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DISEASED_ANY_C = {DISEASED, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DISGUISED_ANY_B = {DISGUISED, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] DISGUISED_ANY_A = {DISGUISED, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] DISGUISED_ANY_C = {DISGUISED, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DISGUISED_ANY_D = {DISGUISED, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DOOMED_ANY_B = {DOOMED, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] DOOMSAYING_ANY_A = {DOOMSAYING, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] DRUNKEN_ANY_D = {DRUNKEN, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] DRUNKEN_ANY_C = {DRUNKEN, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] DYING_ANY_C = {DYING, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] ENCHANTED_ANY_A = {ENCHANTED, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] ENCHANTED_ANY_C = {ENCHANTED, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] EVIL_ANY_B = {EVIL, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] EVIL_ANY_M = {EVIL, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] FALSE_ANY_A = {FALSE, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FOOLISH_ANY_A = {FOOLISH, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FOOLISH_ANY_D = {FOOLISH, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] FRIENDLY_ANY_A = {FRIENDLY, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] FRIENDLY_ANY_C = {FRIENDLY, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] GARRULOUS_ANY_A = {GARRULOUS, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] GREEDY_ANY_D = {GREEDY, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] HANDSOME_ANY_A = {HANDSOME, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] HAPPY_ANY_D = {HAPPY, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] HEALER_ANY_A = {HEALER, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] HEARTRENDING_ANY_C = {HEARTRENDING, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] HIDEOUS_ANY_C = {HIDEOUS, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] HYPNOTIC_ANY_C = {HYPNOTIC, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] IMPRISONED_ANY_A = {IMPRISONED, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] IMPUDENT_ANY_C = {IMPUDENT, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] INSANE_ANY_C = {INSANE, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] KINDLY_ANY_B = {KINDLY, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] KINDLY_ANY_M = {KINDLY, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] LEARNED_ANY_M = {LEARNED, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] LEARNED_ANY_B = {LEARNED, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] LONELY_ANY_A = {LONELY, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LOST_ANY_A = {LOST, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] LOVESICK_ANY_B = {LOVESICK, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] LOVESICK_ANY_M = {LOVESICK, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] LOVESICK_ANY_D = {LOVESICK, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] LOVESICK_ANY_C = {LOVESICK, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] LOVESICK_ANY_A = {LOVESICK, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] MAD_ANY_B = {MAD, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] MAD_ANY_A = {MAD, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] MAD_ANY_D = {MAD, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] MIGHTY_ANY_B = {MIGHTY, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] NEEDY_ANY_B = {NEEDY, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] NEEDY_ANY_D = {NEEDY, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] NOBLE_ANY_M = {NOBLE, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] NOBLE_ANY_B = {NOBLE, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] POSSESSED_ANY_C = {POSSESSED, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] POWERFUL_ANY_C = {POWERFUL, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] POWERFUL_ANY_A = {POWERFUL, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] POWERFUL_ANY_B = {POWERFUL, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] POWERFUL_ANY_D = {POWERFUL, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] REPENTANT_ANY_D = {REPENTANT, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] RUNAWAY_ANY_D = {RUNAWAY, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] SELFSACRIFICIAL_ANY_B = {SELFSACRIFICIAL, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] SKILLFUL_ANY_D = {SKILLFUL, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] TOOTHLESS_ANY_C = {TOOTHLESS, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] TRAPPED_ANY_B = {TRAPPED, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] TRAPPED_ANY_M = {TRAPPED, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] UGLY_ANY_C = {UGLY, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] VENGEFUL_ANY_B = {VENGEFUL, ANY, ReactionMatrix.MATRIX_LETTER_B};
    public final static String[] VENGEFUL_ANY_A = {VENGEFUL, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] VENGEFUL_ANY_M = {VENGEFUL, ANY, ReactionMatrix.MATRIX_LETTER_M};
    public final static String[] WEALTHY_ANY_A = {WEALTHY, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WEALTHY_ANY_D = {WEALTHY, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] WICKED_ANY_A = {WICKED, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WICKED_ANY_C = {WICKED, ANY, ReactionMatrix.MATRIX_LETTER_C};
    public final static String[] WICKED_ANY_D = {WICKED, ANY, ReactionMatrix.MATRIX_LETTER_D};
    public final static String[] WISE_ANY_A = {WISE, ANY, ReactionMatrix.MATRIX_LETTER_A};
    public final static String[] WISE_ANY_D = {WISE, ANY, ReactionMatrix.MATRIX_LETTER_D};

    public static int toMatrixIdx(String strMatrixName)
            throws IllegalArgumentException {

        if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_A)) {
            return 0;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_B)) {
            return 1;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_C)) {
            return 2;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_D)) {
            return 3;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_E)) {
            return 4;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_F)) {
            return 5;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_G)) {
            return 6;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_H)) {
            return 7;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_I)) {
            return 8;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_J)) {
            return 9;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_K)) {
            return 10;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_L)) {
            return 11;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_M)) {
            return 12;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_N)) {
            return 13;
        } else if (0 == strMatrixName.compareTo(ReactionMatrix.MATRIX_LETTER_O)) {
            return 14;
        } else
            throw new IllegalArgumentException();
    }

    public String getAdj()
            throws ArrayIndexOutOfBoundsException {
        return this.get(ADJ_IDX);
    }

    public String getSubj()
            throws ArrayIndexOutOfBoundsException {
        return this.get(SUBJ_IDX);
    }

    public String getMatrixName()
            throws ArrayIndexOutOfBoundsException {
        return this.get(MATRIX_LETTER_IDX);
    }
}
